import { StyleSheet } from 'react-native';
import { getHeight, getWidth } from '../../constants/utils/Dimensions';
import { Colors } from '../../constants/Colors';
import { fontSize } from '../../constants/FontSizes';
import { fontsfamily } from '../../constants/FontFamily';

export const styles = StyleSheet.create({
  btnBackLeft: {
    backgroundColor: Colors.white,
    height: getHeight(36),
    width: getWidth(36),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  kitnamearray: {
    color: Colors.gray0F,
    fontFamily: fontsfamily.gsemiBold,
    fontSize: fontSize.size20,
    letterSpacing: 0.3,
    marginBottom: getHeight(12),
    marginTop: getHeight(24),
  },
  veOrderIdKitDetails: {
    marginHorizontal: getWidth(16),
    marginTop: getHeight(11),
  },
  lblOrderId: {
    color: Colors.gray55,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    marginLeft: getWidth(12),
    letterSpacing: 0.2,
  },
  kitandtestdetails: {
    color: Colors.gray55,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
    marginLeft: getWidth(12),
  },
  vwAnlysisOfAndDate: {
    position: 'absolute',
    bottom: 22,
    left: 21,
  },
  lblAnalysisOf: {
    color: Colors.blue002,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
  },
  lblOrderPlaceDate: {
    color: Colors.blue002,
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size36,
    letterSpacing: 0.2,
  },
  lblCurrency: {
    textAlign: 'right',
    marginRight: getWidth(17),
    marginTop: getHeight(24),
    color: Colors.blue002,
    fontFamily: fontsfamily.gbold,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
  },
  imgKitAnalysisBack: {
    height: getHeight(238),
    marginHorizontal: getWidth(16),
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    overflow: 'hidden',
    marginTop: getHeight(11),
  },
  lblseefullpicture: {
    color: Colors.blue002,
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size14,
  },
  lblOpenMap: {
    color: Colors.black12,
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size14,
    letterSpacing: 0.1,
  },
  lblLeboName: {
    color: Colors.blue0019,
    fontFamily: fontsfamily.gbold,
    letterSpacing: 0.1,
    fontSize: fontSize.size14,
  },
  txtinvitefriendTitle: {
    letterSpacing: 0.2,
    color: Colors.blue0019,
    fontFamily: fontsfamily.gbold,
    fontSize: fontSize.size14,
    marginRight: getWidth(12),
  },
  txtInvoteFriendSubtitle: {
    letterSpacing: 0.1,
    color: Colors.blue0019,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    marginRight: getWidth(12),
  },
  btnInviteFriend: {
    backgroundColor: Colors.white80,
    paddingVertical: getHeight(9),
    paddingHorizontal: getWidth(12),
    justifyContent: 'center',
    alignSelf: 'flex-start',
    alignItems: 'center',
    borderRadius: 20,
    marginTop: getHeight(16),
  },
  vwInBank: { gap: getHeight(2), flex: 1 },
  vwInviteDetails: {
    marginHorizontal: getWidth(16),
    gap: getWidth(6),
    marginTop: getHeight(24),
    backgroundColor: Colors.blueD1,
    borderRadius: 28,
    flexDirection: 'row',
    paddingHorizontal: getWidth(20),
    paddingVertical: getHeight(20),
  },
  starRow: {
    flexDirection: 'row',
  },
  lblTitle: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gregular,
    color: Colors.gray75,
    letterSpacing: 0.1,
  },
  lblSubtitle: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gmedium,
    color: Colors.gray0F,
    letterSpacing: 0.2,
  },
  vwMain: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.whiteF2,
    paddingHorizontal: getWidth(16),
    paddingBottom: getWidth(10),
    justifyContent: 'space-between',
  },
  btnBack: {
    backgroundColor: Colors.blueD1,
    paddingVertical: getHeight(9),
    paddingHorizontal: getWidth(12),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lblInformation: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gbold,
    color: Colors.gray0F,
    letterSpacing: 0.2,
  },
  lblKitName: {
    fontSize: fontSize.size28,
    fontFamily: fontsfamily.bold,
    color: Colors.gray0F,
  },
  lblWithDrawDate: {
    marginTop: 4,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
    color: Colors.gray55,
  },
  lblKitId: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
    color: Colors.gray55,
  },
  lblDataSaveDes: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
    color: Colors.gray2A,
    letterSpacing: 0.1,
  },
});
