import { StyleSheet } from 'react-native';
import { getHeight, getWidth } from '../../../constants/utils/Dimensions';
import { Colors } from '../../../constants/Colors';
import { fontSize } from '../../../constants/FontSizes';
import { fontsfamily } from '../../../constants/FontFamily';

export const styles = StyleSheet.create({
  lblNoAddressFound: {
    fontSize: fontSize.size20,
    textAlign: 'center',
    marginHorizontal: getWidth(40),
    fontFamily: fontsfamily.gsemiBold,
    color: Colors.blue002,
  },
  vwTestReports: {},
  vwSeeall: {
    flexDirection: 'row',
    marginHorizontal: getWidth(16),
    alignItems: 'center',
  },
  seeall: {
    color: Colors.blue002,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gmedium,
    letterSpacing: 0.2,
  },
  vwEmpty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: getHeight(24),
    marginHorizontal: getWidth(16),
  },
  emptyTitle: {
    color: Colors.gray0F,
    fontSize: fontSize.size24,
    fontFamily: fontsfamily.bold,
    textAlign: 'center',
  },
  emptySubtitle: {
    letterSpacing: 0.2,
    color: Colors.gray55,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
    textAlign: 'center',
  },
  itemRow: {
    flexDirection: 'row',
    padding: 6,
    gap: getWidth(6),
    width: getWidth(146),
  },
  selectedRow: {
    borderRadius: 8,
    paddingHorizontal: getWidth(10),
    paddingVertical: getHeight(8),
    backgroundColor: Colors.grayED,
  },
  itemText: {
    textAlign: 'left',
    color: Colors.gray2A,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
  },
  selectedText: {
    textAlign: 'left',
    color: Colors.gray2A,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
  },
  lblWaitingForResult: {
    marginTop: getHeight(12),
    color: Colors.gray0F,
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.bold,
  },
  textinputsearch: {
    margin: 0,
    padding: 0,
    flex: 1,
    color: Colors.gray0F,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
  },
  vwTextinputIcon: {
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    paddingHorizontal: getWidth(12),
    height: getHeight(36),
    alignItems: 'center',
    borderRadius: 999,
    elevation: 4,
    flex: 1,
    flexDirection: 'row',
    gap: getWidth(8),
  },
  btnClose: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 4,
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    // padding: 8,
    height:getHeight(36),
    width:getWidth(36),
    borderRadius: 20,
  },
  vwMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: getWidth(15),
    backgroundColor: Colors.whiteF2,
    paddingHorizontal: getWidth(16),
    paddingBottom: getWidth(10),
  },
  latestanlaysis: {
    flex: 1,
    color: Colors.gray0F,
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.gsemiBold,
    letterSpacing: 0.3,
  },
  lblHeaderTitle: {
    color: Colors.gray0F,
    fontSize: fontSize.size24,
    fontFamily: fontsfamily.gmedium,
  },
  lblSearchProfile: {
    color: Colors.gray0F,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
  },
  vwHeaderRight: { flexDirection: 'row', gap: getWidth(8) },
  vwHeaderbtn: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    height: getHeight(36),
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  vwHeaderbtnSearch: {
    paddingHorizontal: getWidth(12),
    flexDirection: 'row',
    gap: getWidth(6),
    backgroundColor: Colors.white,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  vwHeaderText: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: getWidth(6),
    justifyContent: 'flex-start',
  },
});
