import { StyleSheet } from 'react-native';
import { Colors } from '../../../constants/Colors';
import { getHeight, getWidth } from '../../../constants/utils/Dimensions';
import { fontsfamily } from '../../../constants/FontFamily';
import { fontSize } from '../../../constants/FontSizes';

export const styles = StyleSheet.create({
  //TAB SELECT
  lblNoAddressFound: {
    fontSize: fontSize.size20,
    textAlign: 'center',
    marginHorizontal: getWidth(40),
    fontFamily: fontsfamily.gsemiBold,
    color: Colors.blue002,
  },
  btnAnlaiti: {
    flexDirection: 'row',
    gap: getWidth(6),
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    height: getHeight(34),
    borderRadius: getWidth(10),
    marginVertical: getHeight(4),
  },
  btncheckup: {
    flexDirection: 'row',
    gap: getWidth(6),
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    height: getHeight(34),
    borderRadius: getWidth(10),
    marginVertical: getHeight(4),
  },
  vwCheckupAnaliti: {
    marginTop: getHeight(13),
    backgroundColor: Colors.grayE7,
    marginHorizontal: getWidth(16),
    borderRadius: getWidth(14),
    flexDirection: 'row',
    height: getHeight(42),
    alignItems: 'center',
    paddingHorizontal: getWidth(4),
  },
  lblCheckup: {
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size14,
    letterSpacing:0.1,
    color: Colors.grayE7,
  },
  lblAnaliti: {
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    letterSpacing:0.1,
    color: Colors.grayE7,
  },
  //TAB SELECT END
  vwMainModelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: getWidth(15),
    marginTop: getHeight(5),
    marginHorizontal: getWidth(12),
    paddingBottom: getWidth(10),
  },
  btnBack: {
    backgroundColor: Colors.white,
    height: getHeight(36),
    width: getWidth(36),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  vwHeadingLine: {
    height: getHeight(4),
    width: getWidth(40),
    backgroundColor: Colors.grayED,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: getHeight(6),
  },
  vwTextCount: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.redCA,
    borderRadius: 999,
    // height: getHeight(16),
    paddingVertical: getHeight(1.5),
    paddingHorizontal: getWidth(4.5),
    position: 'absolute',
    right: -2,
    top: -4,
    aspectRatio: 1,
  },
  labelTextCount: {
    color: Colors.white,
    fontSize: fontSize.size10,
    fontFamily: fontsfamily.medium,
  },
  textinputsearch: {
    margin: 0,
    padding: 0,
    flex: 1,
    color: Colors.gray0F,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
  },
  vwTextinputIcon: {
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    paddingHorizontal: getWidth(12),
    height: getHeight(36),
    alignItems: 'center',
    borderRadius: 999,
    elevation: 4,
    flex: 1,
    flexDirection: 'row',
    gap: getWidth(8),
  },
  btnClose: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    // padding: 8,
    height:getHeight(36),
    width:getWidth(36),
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
  },
  vwHeaderRight: { flexDirection: 'row', gap: getWidth(8) },
  vwHeaderbtn: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    height: getHeight(36),
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  vwHeaderText: {
    flex: 1,
    justifyContent: 'center',
  },
  vwMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: getWidth(15),
    backgroundColor: Colors.whiteF2,
    paddingHorizontal: getWidth(16),
  },
  lblHeaderTitle: {
    color: Colors.gray0F,
    fontSize: fontSize.size24,
    fontFamily: fontsfamily.bold,
  },
  //filters
  heading: {
    color: Colors.gray0F,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.bold,
    marginBottom: getHeight(12),
  },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: getWidth(8) },
  chip: {
    paddingHorizontal: getWidth(16),
    paddingVertical: getHeight(9),
    borderRadius: 999,
    backgroundColor: Colors.grayF3,
  },
  chipSelected: {
    backgroundColor: Colors.lightBlurE4,
  },
  chipText: {
    color: Colors.gray0F,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
  },
  chipTextSel: { color: Colors.blue0D },

  applyBtn: {
    marginTop: 40,
    backgroundColor: '#1A73E8',
    paddingVertical: 14,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyText: { color: 'white', fontSize: 16, fontWeight: '600' },

  resetText: {
    textAlign: 'center',
    marginTop: 12,
    color: '#7A7A7A',
    fontSize: 15,
  },
});
