import { StyleSheet } from 'react-native';
import {
  getHeight,
  getWidth,
  ScreenDimensions,
} from '../../constants/utils/Dimensions';
import { Colors } from '../../constants/Colors';
import { fontSize } from '../../constants/FontSizes';
import { fontsfamily } from '../../constants/FontFamily';

export const styles = StyleSheet.create({
  btnAnlaiti: {
    flexDirection: 'row',
    gap: getWidth(6),
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    height: getHeight(34),
    borderRadius: getWidth(10),
    marginVertical: getHeight(4),
  },
  btncheckup: {
    flexDirection: 'row',
    gap: getWidth(6),
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    height: getHeight(34),
    borderRadius: getWidth(10),
    marginVertical: getHeight(4),
  },
  vwCheckupAnaliti: {
    marginTop: getHeight(30),
    backgroundColor: Colors.grayE7,
    marginHorizontal: getWidth(16),
    borderRadius: getWidth(14),
    flexDirection: 'row',
    height: getHeight(42),
    alignItems: 'center',
    paddingHorizontal: getWidth(4),
  },
  lblCheckup: {
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size14,
    letterSpacing:0.1,
    color: Colors.grayE7,
  },
  lblAnaliti: {
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    letterSpacing:0.1,
    color: Colors.grayE7,
  },
  orderhistoryemptysubtitle: {
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    color: Colors.gray55,
    letterSpacing: 0.1,
    textAlign: 'center',
    marginBottom: getHeight(24),
  },
  orderhistoryemptytitle: {
    marginTop: getHeight(36),
    fontFamily: fontsfamily.gsemiBold,
    fontSize: fontSize.size20,
    color: Colors.gray0F,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  emptyview: {
    flex:1,
    backgroundColor:Colors.whiteF2,
    paddingHorizontal: getWidth(16),
    paddingTop:getHeight(70),
    alignItems: 'center',
    // justifyContent: 'center',
  },
  vwHeaderTitle: {},
  lblGoToCart: {
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size16,
    color: Colors.white,
    letterSpacing: 0.2,
  },
  kittitle: {
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size36,
    color: Colors.blue002,
    letterSpacing: 0.1,
    marginTop: getHeight(7),
  },
  kitsubtitle: {
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    color: Colors.blue002,
    letterSpacing: 0.2,
  },
  imgkitdetails: {
    justifyContent: 'flex-end',
    marginTop: getHeight(21),
    marginHorizontal: getWidth(16),
    backgroundColor: Colors.white,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    padding: 21,
  },
  vwKitDeatils: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lblKitTitleInner: {
    color: Colors.gray0F,
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.gsemiBold,
    marginHorizontal: getWidth(16),
    marginTop: getHeight(23),
    letterSpacing: 0.3,
  },
  lblKittitleModel: {
    color: Colors.white,
    fontSize: fontSize.size36,
    fontFamily: fontsfamily.gmedium,
  },
  lblKitselectTitle: {
    color: Colors.white,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
  },
  vwError: {
    marginTop: getHeight(6),
    gap: getWidth(4),
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: getWidth(16),
  },
  lablWarning: {
    color: Colors.red8C,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.medium,
  },
  lblTitleInput: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
    color: Colors.gray55,
    marginBottom: getHeight(6),
  },
  vwSwitchcontainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: getWidth(12),
    marginTop: getHeight(14),
  },
  lblSwitchTitle: {
    flex: 1,
    marginRight: getWidth(10),
    fontSize: fontSize.size16,
    color: Colors.gray0F,
    fontFamily: fontsfamily.gmedium,
  },
  vwInputsInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getWidth(10),
  },
  vwMainAddAddress: {
    marginTop: getHeight(14),
    marginHorizontal: getWidth(15),
  },
  lblAddAddressPopupTitle: {
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    color: Colors.gray55,
    letterSpacing: 0.2,
  },
  vwCartImage: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: getWidth(8),
  },
  vwPrice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getWidth(5),
  },
  vwGoToCart: {
    width: ScreenDimensions.screenWidth - getWidth(32),
    alignSelf: 'center',
    borderRadius: 20,
    alignItems: 'center',
    position: 'absolute',
    height: getHeight(48),
    paddingHorizontal: getWidth(16),
    backgroundColor: Colors.blue002,
    flexDirection: 'row',
  },
  disprice: {
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size16,
    color: Colors.white36,
    textDecorationLine: 'line-through',
  },
  totalprice: {
    letterSpacing: 0.2,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    color: Colors.white,
  },
  lblInTheCart: {
    fontSize: fontSize.size24,
    fontFamily: fontsfamily.bold,
    color: Colors.gray0F,
    marginHorizontal: getWidth(16),
    marginBottom: getHeight(12),
  },
  vwBottomBtn: {
    marginTop: getHeight(16),
    gap: getHeight(8),
  },
  lblwhodothetest: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
    letterSpacing: 0.1,
    color: Colors.gray55,
  },
  vwImgBack: {
    marginTop: getHeight(12),
    borderRadius: 24,
    padding: 16,
    overflow: 'hidden',
  },
  vwDateTimeMain: {
    backgroundColor: Colors.redFC,
    padding: 4,
    borderRadius: 20,
    marginTop: getHeight(4),
  },
  vwDateTimeInner: {
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: Colors.redCA,
    borderRadius: 20,
    paddingVertical: getHeight(12),
    paddingHorizontal: getWidth(16),
    backgroundColor: Colors.white,
  },
  vwInputDiscountInner: {
    flex: 1,
    margin: 0,
    padding: 0,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
    color: Colors.black,
    letterSpacing: 0.2,
    marginRight: getWidth(10),
  },
  summaryContainer: {
    marginTop: getHeight(24),
  },
  summaryInnerContainer: {
    backgroundColor: Colors.grayE7,
    padding: 20,
    marginTop: getHeight(10),
    borderRadius: 20,
    gap: getHeight(8),
  },
  summaryTitle: {
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.gsemiBold,
    letterSpacing: 0.3,
    color: Colors.gray0F,
  },
  summarySubtitle: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gregular,
    letterSpacing: 0.1,
    color: Colors.gray55,
  },
  summaryItemRow: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
  },
  summaryLabel: {
    flex: 1,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
    letterSpacing: 0.2,
    color: Colors.gray55,
  },
  summaryValue: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
    letterSpacing: 0.2,
    color: Colors.gray0F,
  },
  discountContainer: {
    // marginTop: 16,
  },
  discountLabel: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.regular,
    letterSpacing: 0.2,
    color: Colors.gray0F,
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray0F,
    borderRadius: 12,
    overflow: 'hidden',
  },
  vwHeaderLeft: {
    flexDirection: 'row',
    gap: getWidth(8),
  },
  vwMainModelHeader: {
    paddingTop: getHeight(10),
    marginHorizontal: getWidth(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vwMainModelHeaderTestDetails: {
    paddingTop: getHeight(10),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vwMainModelHeaderEditAnliti: {
    paddingTop: getHeight(10),
    marginHorizontal: getWidth(16),
  },
  vwMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: getWidth(15),
    backgroundColor: Colors.whiteF2,
    paddingBottom: getWidth(10),
  },
  vwInputDisocunt: {
    flexDirection: 'row',
    height: getHeight(56),
    borderRadius: 12,
    marginTop: getHeight(6),
    paddingHorizontal: getWidth(12),
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 2,
    borderColor: Colors.grayD8,
  },
  vwInput: {
    height: getHeight(56),
    borderRadius: 12,
    marginTop: getHeight(6),
    paddingHorizontal: getWidth(12),
    // flex: 1,
    margin: 0,
    padding: 0,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderWidth: 2,
    borderColor: Colors.grayD8,
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
    color: Colors.black,
    letterSpacing: 0.2,
  },
  vwSave: {
    backgroundColor: Colors.lightBlurE4,
    height: getHeight(36),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: getWidth(12),
    borderRadius: 20,
  },
  vwHelp: {
    backgroundColor: Colors.white,
    height: getHeight(36),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: getWidth(13),
    borderRadius: 20,
    flexDirection: 'row',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  btnEdit: {
    backgroundColor: Colors.blue002,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    height: getHeight(48),
    borderRadius: 20,
    gap: getWidth(6),
    marginTop: getHeight(12),
  },
  btnBack: {
    backgroundColor: Colors.white,
    height: getHeight(36),
    width: getWidth(36),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  btnChange: {
    backgroundColor: Colors.white64,
    height: getHeight(36),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: getWidth(12),
  },
  btnAdd: {
    backgroundColor: Colors.blueD1,
    paddingVertical: getHeight(9),
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: getWidth(12),
  },
  lblSave: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
    color: Colors.blue17,
  },
  lblHomeService: {
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.gsemiBold,
    color: Colors.gray0F,
  },
  lblDateAndTime: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gregular,
    color: Colors.gray75,
  },
  lblDateAndTimeValue: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gmedium,
    color: Colors.gray0F,
  },
  lblHaveYouCoupans: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
    color: Colors.gray55,
  },
  lblYourOrder: {
    fontSize: fontSize.size28,
    fontFamily: fontsfamily.gmedium,
    color: Colors.gray0F,
  },
  lblYourOrderSubtitle: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gregular,
    color: Colors.gray55,
    letterSpacing: 0.2,
  },
  lblAddtionalInstructions: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
    color: Colors.gray55,
    letterSpacing: 0.1,
  },
  lblChnage: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gmedium,
    color: Colors.blue002,
    letterSpacing: 0.1,
  },
  lblHelp: {
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.medium,
    color: Colors.gray0F,
  },
  lblEdit: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.gmedium,
    color: Colors.white,
    letterSpacing: 0.2,
  },
  //model
  overlay: {
    flex: 1,
    backgroundColor: '#0F0F0F99',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    height: '50%',
  },
  vwHeadingLine: {
    height: getHeight(4),
    width: getWidth(40),
    backgroundColor: Colors.grayED,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: getHeight(6),
  },
});
