import { StyleSheet } from 'react-native';
import { fontSize } from '../../../constants/FontSizes';
import { fontsfamily } from '../../../constants/FontFamily';
import { Colors } from '../../../constants/Colors';
import {
  getHeight,
  getWidth,
  ScreenDimensions,
} from '../../../constants/utils/Dimensions';

export const styles = StyleSheet.create({
  btnBookedExtraCount: {
    backgroundColor: Colors.white08,
    paddingHorizontal: getWidth(8),
    height: getHeight(24),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
    marginRight: getWidth(2),
  },
  vwTagBooked: {
    backgroundColor: Colors.white08,
    paddingHorizontal: getWidth(8),
    height: getHeight(24),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
    marginRight: getWidth(2),
  },
  btnBooked: {
    marginTop: getHeight(8),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backgroundColor: Colors.black04,
    borderRadius: 20,
    padding: 16,
  },
  btnextracount: {
    backgroundColor: Colors.grayF3,
    paddingHorizontal: getWidth(8),
    paddingVertical: getHeight(4),
    borderRadius: 999,
    marginRight: getWidth(2),
  },
  vwBackTagWaiting: {
    backgroundColor: Colors.grayF3,
    paddingHorizontal: getWidth(8),
    height: getHeight(24),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
    marginRight: getWidth(2),
  },
  vwTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: getHeight(5),
  },
  imgkit: {
    height: getHeight(40),
    width: getWidth(40),
    borderRadius: 26,
  },
  btnwaitingview3: {
    gap: getHeight(10),
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Colors.blue6B,
    paddingHorizontal: getWidth(16),
    paddingTop: getHeight(16),
    paddingBottom: getHeight(12),
    flexDirection: 'row',
  },
  btnwaitingview2: {
    backgroundColor: Colors.blue1C08,
    padding: 4,
    borderRadius: 20,
  },
  btnwaitingview1: {
    backgroundColor: Colors.blue1C04,
    padding: 4,
    borderRadius: 20,
    marginTop: getHeight(3),
  },
  lblKitsandAnaliti: {
    color: Colors.gray75,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    letterSpacing: 0.1,
  },
  lblTestImage: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  blTestImage: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lblTotalAnalysis: {
    color: Colors.blue002,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
  },
  lblCurrentanalysis: {
    letterSpacing: 0.2,
    color: Colors.blue002,
    fontFamily: fontsfamily.gbold,
    fontSize: fontSize.size16,
  },
  lblTestName: {
    flex: 1,
    letterSpacing: 0.2,
    color: Colors.blue002,
    fontFamily: fontsfamily.gmedium,
    fontSize: fontSize.size16,
  },
  btnTestReport: {
    marginHorizontal: getWidth(16),
    backgroundColor: Colors.white,
    borderRadius: 20,
    paddingVertical: getHeight(12),
    paddingHorizontal: getWidth(16),
    gap: getHeight(7),
  },

  lblKitAndTestName: {
    maxWidth:200,
    color: Colors.gray55,
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.gregular,
    letterSpacing: 0.1,
  },
  lblDateyear: {
    color: Colors.gray0F,
    fontSize: fontSize.size14,
    fontFamily: fontsfamily.gregular,
    letterSpacing: 0.1,
  },
  vwLightBlue: {
    backgroundColor: Colors.blueD1,
    height: getHeight(37),
    aspectRatio: 1,
    borderRadius: 100,
  },
  lblWaitingForResult: {
    color: Colors.gray0F,
    fontSize: fontSize.size20,
    fontFamily: fontsfamily.bold,
  },
  progressBarContainer: {
    flexDirection: 'row',
    gap: 4,
    marginRight: getWidth(141),
  },
  progressStep: {
    height: 4,
    flex: 1,
    backgroundColor: Colors.grey29,
    borderRadius: 2,
  },
  progressStepActive: {
    backgroundColor: Colors.blue3C,
  },
  vwMainOrderDetails: {
    flexDirection: 'row',
  },
  nurseview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getWidth(4),
    marginTop: getHeight(10),
  },
  starRow: {
    flexDirection: 'row',
  },
  vwstatusReport: {
    backgroundColor: Colors.lightBlurE4,
    borderRadius: 999,
    paddingVertical: getHeight(5),
    paddingHorizontal: getWidth(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  lblTag: {
    color: Colors.gray0F,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size12,
    letterSpacing: 0.1,
  },
  lblOrderTitleBooked: {
    color: Colors.white,
    fontFamily: fontsfamily.gbold,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
    flex: 1,
  },
  lblOrderTitle: {
    color: Colors.gray0F,
    fontFamily: fontsfamily.bold,
    fontSize: fontSize.size16,
    letterSpacing: 0.2,
  },
  lblOrderDesBooked: {
    marginTop: getHeight(6),
    color: Colors.gray75,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    letterSpacing: 0.1,
  },
  lblOrderDate: {
    color: Colors.gray55,
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size14,
    letterSpacing: 0.1,
  },
  lblOrderID: {
    color: Colors.gray75,
    fontFamily: fontsfamily.gregular,
    fontSize: fontSize.size14,
    letterSpacing: 0.1,
  },
  lblStatus: {
    color: Colors.blue1C,
    fontFamily: fontsfamily.medium,
    fontSize: fontSize.size12,
  },
  lblReportTitle: {
    color: Colors.gray0F,
    fontFamily: fontsfamily.bold,
    fontSize: fontSize.size16,
  },
  lblLastValue: {
    color: Colors.gray55,
    fontFamily: fontsfamily.regular,
    fontSize: fontSize.size12,
  },
  vwReportDate: {
    gap: getWidth(11),
    flexDirection: 'row',
    paddingLeft: getWidth(8),
    paddingRight: getWidth(31),
    paddingVertical: getHeight(8),
    // width: ScreenDimensions.screenWidth * 0.60,
    borderRadius: 20,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lblReportName: {
    fontSize: fontSize.size16,
    fontFamily: fontsfamily.medium,
    color: Colors.gray0F,
  },
  lblDate: {
    fontSize: fontSize.size12,
    fontFamily: fontsfamily.regular,
    color: Colors.gray55,
  },
});
